const STATE_TO_VERIFY = 1;
const STATE_VERIFIED = 3;
const STATE_REJECTED = -1;
const STATE_ARCHIVE = 2;

exports.STATE_TO_VERIFY=STATE_TO_VERIFY
exports.STATE_VERIFIED=STATE_VERIFIED
exports.STATE_REJECTED=STATE_REJECTED
exports.STATE_ARCHIVE=STATE_ARCHIVE