const  testtt = require("./function.js") 
// testtt.add_product("ff", 228, Date.now(),Date.now())
// testtt.filter_by_name("123").then(res => console.log(res[0].id))
// testtt.filter_by_article(2).then(res => console.log(res[0].article))
// testtt.filter_by_data_creating(Date.now()).then(res => console.log(res[0].data_creating))
// testtt.filter_by_expiration_date(Date.now()).then(res => console.log(res[0].expiration_date))
// testtt.filter_by_data_shop(Date.now()).then(res => console.log(res[0].data_shop))
// testtt.delete_product("123", 2, Date.now(),Date.now())